enum Survivor {
  dwightFairfield,
  megThomas,
  claudetteMorel,
  jakePark,
  neaKarlsson,
  laurieStrode,
  aceVisconti,
  billOverbeck,
  fengMin,
  davidKing,
  quentinSmith,
  davidTapp,
  kateDenson,
  adamFrancis,
  jeffJohansen,
  janeRomero,
  ashWilliams,
  nancyWheeler,
  steveHarrington,
  yuiKimura,
  zarinaKassir,
  cherylMason,
  felixRichter,
  elodieRakoto,
  yunJinLee,
  jillValentine,
  leonScottKennedy,
  mikaelaReid,
  jonahVasquez,
  yoichiAsakawa,
  haddieKaur,
  adaWong,
  rebeccaChambers,
  vittorioToscano,
}

export default Survivor;
